# Generated by Django 4.1.7 on 2023-04-04 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_university_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 12, 33, 15, 883115)),
        ),
    ]
